openapi: 3.0.0
info:
  title: WxO SF Services
  description: WxO SF Services
  version: '1.0'
servers:
  - url: https://wxo-sf-services.1d13bpwyy9q7.us-east.codeengine.appdomain.cloud
paths:
  /top_accounts:
    get:
      summary: Accounts with largest revenue
      description: Get a list of accounts with the largest revenue
      operationId: top_accounts
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountList'
components:
  schemas:
    Account:
      properties:
        id:
          type: string
          title: Id
        name:
          type: string
          title: Name
        revenue:
          type: number
          title: Revenue
      type: object
      required:
        - id
        - name
        - revenue
      title: Account
    AccountList:
      properties:
        totalSize:
          type: integer
          title: Totalsize
        records:
          items:
            $ref: '#/components/schemas/Account'
          type: array
          title: Records
      type: object
      required:
        - totalSize
        - records
      title: AccountList
  securitySchemes:
    HTTPBasic:
      type: http
      scheme: basic