openapi: 3.0.0
info:
  title: WxO SF Services
  description: WxO SF Services
  version: '1.0'
servers:
  - url: https://wxo-sf-services.1d13bpwyy9q7.us-east.codeengine.appdomain.cloud
paths:
  /top_accounts:
    get:
      summary: Accounts with largest revenue
      description: Get a list of accounts with the largest revenue
      operationId: top_accounts
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountList'
  /contacts:
    get:
      summary: Contacts for Account
      description: Get a list of contacts for an account
      operationId: contacts_by_account
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
            title: Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactList'
components:
  schemas:
    Account:
      properties:
        id:
          type: string
          title: Id
        name:
          type: string
          title: Name
        revenue:
          type: number
          title: Revenue
      type: object
      required:
        - id
        - name
        - revenue
      title: Account
    AccountList:
      properties:
        totalSize:
          type: integer
          title: Totalsize
          x-ibm-show: false
        records:
          items:
            $ref: '#/components/schemas/Account'
          type: array
          title: Records
      type: object
      required:
        - totalSize
        - records
      title: AccountList
    Contact:
      properties:
        name:
          type: string
          title: Name
        title:
          type: string
          title: Title
        email:
          type: string
          title: Email
      type: object
      required:
        - name
        - title
        - email
      title: Contact
    ContactList:
      properties:
        totalSize:
          type: integer
          title: Totalsize
          x-ibm-show: false
        records:
          items:
            $ref: '#/components/schemas/Contact'
          type: array
          title: Records
      type: object
      required:
        - totalSize
        - records
      title: ContactList
  securitySchemes:
    HTTPBasic:
      type: http
      scheme: basic