openapi: 3.0.0
info:
  title: WxO SF Services
  description: WxO SF Services
  version: '1.0'
  x-ibm-application-icon: <svg id="Layer_1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 54 52.18"><text transform="translate(0 40.18)" style="fill:#2e3192; font-family:MyriadPro-Regular, &apos;Myriad Pro&apos;; font-size:48px;"><tspan x="0" y="0">L3</tspan></text></svg>
servers:
  - url: https://wxo-l3-services.1d13bpwyy9q7.us-east.codeengine.appdomain.cloud
paths:
  /top_accounts:
    get:
      summary: Accounts with largest revenue
      description: Get a list of accounts with the largest revenue
      operationId: top_accounts
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountList'
      security:
        - HTTPBasic: []
components:
  schemas:
    Account:
      properties:
        name:
          type: string
          title: Name
        revenue:
          type: number
          title: Revenue
      type: object
      required:
        - name
        - revenue
      title: Account
    AccountList:
      properties:
        totalSize:
          type: integer
          title: Totalsize
          x-ibm-show: false
        records:
          items:
            $ref: '#/components/schemas/Account'
          type: array
          title: Records
      type: object
      required:
        - totalSize
        - records
      title: AccountList
  securitySchemes:
    HTTPBasic:
      type: http
      scheme: basic